# Generated by Django 5.2 on 2025-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('URGENTE', 'Urgente'), ('PENDIENTE', 'Pendiente'), ('OPCIONAL', 'Opcional')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='NUEVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='vehiculo',
        ),
    ]
